import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>OldDragon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main className={styles.main}>
        <header className={styles.header}>
          <img className={styles.img} src="/Logo-Fundo-Claro.png" />
          <a href='/login'><button className={styles.button}>Login</button></a>
          <a href='/cadastro'><button className={styles.button}>Cadastro</button></a>
        </header>

        <div className={styles.container}>
        <h2 className={styles.h2}>QUE AVENTURAS TE ESPERAM?</h2>
        </div>
      </main>
    </div>
  )
}

export default Home
